version: '3'
services:
  btcd:
    image: btcd
    build:
      context: btcd/
    volumes:
      - btcd_rpc:/rpc
      - btcd_data:/data
    environment:
      RPCUSER:
      RPCPASS:
    ports:
      - 8333:8333  # peer
      - 8334:8334  # rpc
    restart: always

  lnd:
    hostname: lnd
    build:
      context: lnd/
    volumes:
      - btcd_rpc:/rpc
      - lnd:/root/.lnd/
    ports:
      - 9735:9735
    environment:
      NETWORK: mainnet
      RPCUSER:
      RPCPASS:
      EXTERNAL_IP:
    depends_on:
      - btcd
    restart: always

volumes:
  btcd_rpc:
    driver: local

  btcd_data:
    driver: local

  lnd:
    driver: local
