version: '3'
services:
  btcd:
    image: btcd
    build:
      context: btcd/
    volumes:
      - btcd_rpc:/rpc
      - btcd_data:/data
    environment:
      RPCUSER:
      RPCPASS:
    ports:
      - 8333:8333  # peer
      - 8334:8334  # rpc
    restart: always

volumes:
  btcd_rpc:
    driver: local

  btcd_data:
    driver: local
